### ISSUE TITLE
jinja2에서 list array변수 참조하는 방법

### ISSUE THREAD

**Issue by cesdea** [unchaptered/coffee-selector#15]
> {% for  arr in list %}
>>{{ arr.name }}
>>{{ arr.desc }}
>>{{ arr.option }}
>{% endfor %}
이런식으로 list는 배열로 취급해서 arr를 받아오고 arr를 리스트로 취급해서 사용한다.

**Comment by unchaptered** [comment]
헉 감사합니다!
