### ISSUE TITLE
Flask 사진 업로드 문제

### ISSUE THREAD

**Issue by cesdea** [unchaptered/coffee-selector#19]
flask가 html이나 css에서 내부 파일인 사진을 올리려고하면 오류가 나오는데
해결방법은 서버에서 상대 주소로 사진을 보내서 쓰는것이다.

**Comment by unchaptered** [comment]
app.py 에서 넣는 방법 에서 index.html 에서 `static/index.png` 파일을 가져오는 문제가 해결되었습니다.

이번 [풀 리퀘스트 - Flask-Brypt 를 이용한 비밀번호 암호화](https://github.com/unchaptered/coffee-selector/pull/21) 의 [templates/pages/index.html 수정사항 중 추가된 내용 8번 라인](https://github.com/unchaptered/coffee-selector/pull/21/commits/d6d1754c52fd9916e91336624b4781366be521a0#diff-9ffc9778d2a8b421576a0729b1f5ce370f85df1d635bb3165ce4c98e6540bffd) 에 있는 다음의 코드입니다.

```html
<img src="../../static/index.png" class="image" />
```
